org: raffalcao
console: true
service: sls-mobile-api

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'sa-east-1'}
  memorySize: 128
  timeout: 3

functions:
  index:
    handler: index.handler
    description: Lambda Mobile API
    events:
      - http:
          path: /index
          method: post
      